[package]
name = "baras-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
baras-core = { path = "../core" }
shlex = "1.3.0"
clap = { version = "4.5.53", features = ["derive"] }
tokio = "1.48.0"
chrono = "0.4.42"
