# A Traitor Among The Chiss
# 4 boss(es)

[area]
name = "A Traitor Among The Chiss"
area_id = 833571547775777

# ─── guardian_droid ───
[[boss]]
id = "guardian_droid"
name = "Guardian Droid"
difficulties = ["master", "veteran"]
npc_names = ["Guardian Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "guardian_droid_security_droid"
name = "Security Droid"
trigger = { type = "ability_cast", ability_ids = [4132312589533184] }
duration_secs = 60.0
color = [11, 128, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_tank_droid"
name = "Tank Droid"
trigger = { type = "ability_cast", ability_ids = [4132346949271552] }
duration_secs = 90.0
color = [15, 128, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_explosive_droid"
name = "Explosive Droid"
trigger = { type = "ability_cast", ability_ids = [4132342654304256] }
duration_secs = 15.0
color = [11, 128, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_heat_beam"
name = "Heat Beam"
trigger = { type = "ability_cast", ability_ids = [4134146540568576] }
duration_secs = 15.0
color = [26, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_missile"
name = "Missile"
trigger = { type = "ability_cast", ability_ids = [4134941109518336] }
duration_secs = 20.0
color = [213, 36, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_concussive_blast"
name = "Concussive Blast"
trigger = { type = "ability_cast", ability_ids = [4143492389404672] }
duration_secs = 10.0
color = [220, 93, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_mortar_volley"
name = "Mortar Volley"
trigger = { type = "ability_cast", ability_ids = [4139755767857152] }
duration_secs = 9.0
color = [236, 234, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_proximity_measure"
name = "Proximity Measure"
trigger = { type = "ability_cast", ability_ids = [4132943949725696] }
duration_secs = 20.0
color = [32, 47, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "guardian_droid_incinerate"
name = "Incinerate"
trigger = { type = "ability_cast", ability_ids = [4149080141856768] }
duration_secs = 20.0
color = [220, 93, 32, 255]
difficulties = ["veteran", "master"]

# ─── strike_team_walker ───
[[boss]]
id = "strike_team_walker"
name = "Strike Team Walker"
difficulties = ["master", "veteran"]
npc_names = ["Strike Team Walker"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "strike_team_walker_phase_1"
name = "Phase 1"
trigger = { type = "timer_expires", timer_id = "strike_team_walker_phase_2" }
duration_secs = 60.0
color = [15, 128, 27, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4140206739423232] }
duration_secs = 80.0
color = [15, 128, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_phase_2"
name = "Phase 2"
trigger = { type = "combat_start" }
duration_secs = 60.0
color = [22, 136, 16, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_burst_wave"
name = "Burst Wave"
trigger = { type = "ability_cast", ability_ids = [4143638418292736] }
duration_secs = 22.5
color = [220, 138, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_rain_of_fire"
name = "Rain of Fire"
trigger = { type = "ability_cast", ability_ids = [4138295478976512] }
duration_secs = 7.0
color = [228, 27, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_buf_repair"
name = "Buf + Repair"
trigger = { type = "ability_cast", ability_ids = [4138033485971456] }
duration_secs = 11.0
color = [236, 28, 190, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_shock_and_awe"
name = "Shock and Awe"
trigger = { type = "ability_cast", ability_ids = [4137853097345024] }
duration_secs = 9.0
color = [228, 34, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "strike_team_walker_orbital_laser"
name = "Orbital Laser"
trigger = { type = "ability_cast", ability_ids = [4137865982246912] }
duration_secs = 12.0
color = [228, 125, 27, 255]
difficulties = ["veteran", "master"]

# ─── syndic_zenta ───
[[boss]]
id = "syndic_zenta"
name = "Syndic Zenta"
difficulties = ["master", "veteran"]
npc_names = ["Syndic Zenta"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "syndic_zenta_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [4138836644855808] }
duration_secs = 20.0
color = [217, 26, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_magnetic_charge"
name = "Magnetic Charge"
trigger = { type = "ability_cast", ability_ids = [4136714931011584] }
duration_secs = 11.5
color = [220, 32, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_medic"
name = "Medic"
trigger = { type = "ability_cast", ability_ids = [4137170197544960] }
duration_secs = 60.0
color = [220, 212, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_laser_droid"
name = "Laser Droid"
trigger = { type = "ability_cast", ability_ids = [4136379923562496] }
duration_secs = 60.0
color = [112, 197, 17, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_assassins"
name = "Assassins"
trigger = { type = "ability_cast", ability_ids = [4136414283300864] }
duration_secs = 60.0
color = [7, 128, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4151811741057024] }
duration_secs = 14.0
color = [228, 116, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_snipe"
name = "Snipe"
trigger = { type = "ability_cast", ability_ids = [4140116545110016] }
duration_secs = 11.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_snipers"
name = "Snipers"
trigger = { type = "ability_cast", ability_ids = [4136375628595200] }
duration_secs = 60.0
color = [13, 121, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_static_probe"
name = "Static Probe"
trigger = { type = "ability_cast", ability_ids = [4145493844164608] }
duration_secs = 33.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_assassins_2"
name = "Assassins_"
trigger = { type = "ability_cast", ability_ids = [4140193854521344] }
duration_secs = 40.0
color = [13, 113, 14, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_tank_droids"
name = "Tank Droids"
trigger = { type = "ability_cast", ability_ids = [4136384218529792] }
duration_secs = 60.0
color = [115, 220, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_demo_droid"
name = "Demo Droid"
trigger = { type = "ability_cast", ability_ids = [4149479573815296] }
duration_secs = 40.0
color = [202, 213, 31, 255]
difficulties = ["veteran", "master"]

# ─── valss ───
[[boss]]
id = "valss"
name = "Valss"
difficulties = ["master", "veteran"]
npc_names = ["Valss"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "valss_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4134623281938432] }
duration_secs = 15.0
color = [228, 39, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_bombardment"
name = "Bombardment_"
trigger = { type = "ability_cast", ability_ids = [4136263959445504] }
duration_secs = 30.0
color = [228, 128, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_bombardment_2"
name = "Bombardment"
trigger = { type = "ability_cast", ability_ids = [4134812260499456] }
duration_secs = 39.0
color = [228, 124, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_impulse_2"
name = "Impulse_"
trigger = { type = "ability_cast", ability_ids = [4135396376051712] }
duration_secs = 30.0
color = [220, 26, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_powered_shot"
name = "Powered Shot"
trigger = { type = "ability_cast", ability_ids = [4134503022854144] }
duration_secs = 30.0
color = [220, 26, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_master_stroke"
name = "Master Stroke"
trigger = { type = "ability_cast", ability_ids = [4135435030757376] }
duration_secs = 25.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_mine_primer"
name = "Mine primer"
trigger = { type = "ability_cast", ability_ids = [4147375039840256] }
duration_secs = 79.0
color = [197, 213, 38, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_blizzard_burst"
name = "Blizzard Burst"
trigger = { type = "ability_cast", ability_ids = [4147581198270464] }
duration_secs = 30.0
color = [27, 228, 218, 255]
difficulties = ["veteran", "master"]
