# Athiss
# 4 boss(es)

[area]
name = "Athiss"
area_id = 833571547775683

# ─── ancient_abomination ───
[[boss]]
id = "ancient_abomination"
name = "Ancient Abomination"
difficulties = ["master"]
npc_names = ["Ancient Abomination"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "ancient_abomination_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 240.0
color = [220, 32, 34, 255]
difficulties = ["master"]

[[boss.timer]]
id = "ancient_abomination_smash"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [2535937670119424] }
duration_secs = 20.0
color = [19, 220, 219, 255]
difficulties = ["master"]

# ─── professor_ley_arsha ───
[[boss]]
id = "professor_ley_arsha"
name = "Professor Ley'arsha"
difficulties = ["master", "veteran"]
npc_names = ["Professor Ley'arsha"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "professor_ley_arsha_affliction_field"
name = "Affliction Field"
trigger = { type = "ability_cast", ability_ids = [3228668650323968] }
duration_secs = 12.0
color = [220, 34, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "professor_ley_arsha_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [2315051797053440] }
duration_secs = 31.5
color = [21, 144, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "professor_ley_arsha_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [2211899567505408] }
duration_secs = 31.5
color = [16, 136, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "professor_ley_arsha_blaster_volley"
name = "Blaster Volley"
trigger = { type = "ability_cast", ability_ids = [2263529369370624] }
duration_secs = 7.5
color = [228, 117, 20, 255]
difficulties = ["veteran", "master"]

# ─── prophet_of_vodal ───
[[boss]]
id = "prophet_of_vodal"
name = "Prophet of Vodal"
difficulties = ["master", "veteran"]
npc_names = ["Prophet of Vodal"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "prophet_of_vodal_corruption"
name = "Corruption"
trigger = { type = "ability_cast", ability_ids = [2278832337846272] }
duration_secs = 21.5
color = [19, 159, 35, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2276813703217152] }
duration_secs = 16.0
color = [151, 205, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_corruption_2"
name = "Corruption_"
trigger = { type = "ability_cast", ability_ids = [3229106736988160] }
duration_secs = 30.0
color = [16, 136, 23, 255]
difficulties = ["master"]

[[boss.timer]]
id = "prophet_of_vodal_adds_immunity"
name = "Adds Immunity"
trigger = { type = "effect_applied", effect_ids = [2279489467842560] }
duration_secs = 110.0
color = [26, 216, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_lightning"
name = "Lightning"
trigger = { type = "ability_cast", ability_ids = [2277586797330432] }
duration_secs = 30.0
color = [228, 34, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_affliction_2"
name = "Affliction_"
trigger = { type = "timer_expires", timer_id = "prophet_of_vodal_corruption" }
duration_secs = 10.0
color = [142, 190, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_lightning_affliction"
name = "Lightning + Affliction"
trigger = { type = "timer_expires", timer_id = "prophet_of_vodal_corruption" }
duration_secs = 10.0
color = [220, 28, 26, 255]
difficulties = ["veteran", "master"]

# ─── the_beast_of_vodal_kressh ───
[[boss]]
id = "the_beast_of_vodal_kressh"
name = "The Beast of Vodal Kressh"
difficulties = ["master", "veteran"]
npc_names = ["The Beast of Vodal Kressh"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_beast_of_vodal_kressh_roar"
name = "Roar"
trigger = { type = "ability_cast", ability_ids = [2276418566225920] }
duration_secs = 30.0
color = [190, 157, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_beast_of_vodal_kressh_knockback_right"
name = "Knockback Right"
trigger = { type = "ability_cast", ability_ids = [2275117191135232] }
duration_secs = 15.0
color = [26, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_beast_of_vodal_kressh_knockback_left"
name = "Knockback Left"
trigger = { type = "ability_cast", ability_ids = [2275117191135232] }
duration_secs = 15.0
color = [228, 33, 27, 255]
difficulties = ["veteran", "master"]
