# Battle of Rishi
# 4 boss(es)

[area]
name = "Battle of Rishi"
area_id = 833571547775720

# ─── commander_mokan ───
[[boss]]
id = "commander_mokan"
name = "Commander Mokan"
difficulties = ["master", "veteran"]
npc_names = ["Commander Mokan"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_mokan_compound_17"
name = "Compound 17_"
trigger = { type = "combat_start" }
duration_secs = 35.0
color = [213, 32, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_mokan_compound_17_2"
name = "Compound 17"
trigger = { type = "ability_cast", ability_ids = [3535548358590464] }
duration_secs = 43.0
color = [220, 42, 32, 255]
difficulties = ["veteran", "master"]

# ─── master_obai_and_lord_vodd ───
[[boss]]
id = "master_obai_and_lord_vodd"
name = "Master Obai and Lord Vodd"
difficulties = ["master", "veteran"]
npc_names = ["Master Obai and Lord Vodd"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_obai_and_lord_vodd_forcewave_setup"
name = "Forcewave Setup"
trigger = { type = "ability_cast", ability_ids = [3384494358790144] }
duration_secs = 25.0
color = [171, 220, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_forcewave"
name = "Forcewave"
trigger = { type = "timer_expires", timer_id = "master_obai_and_lord_vodd_forcewave_setup" }
duration_secs = 20.0
color = [192, 228, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_forcewave_2"
name = "Forcewave_"
trigger = { type = "ability_cast", ability_ids = [3382269565730816] }
duration_secs = 20.0
color = [193, 220, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_stun_setup"
name = "Stun Setup"
trigger = { type = "ability_cast", ability_ids = [3385636820090880] }
duration_secs = 23.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_stun"
name = "Stun"
trigger = { type = "timer_expires", timer_id = "master_obai_and_lord_vodd_stun_setup" }
duration_secs = 22.0
color = [220, 28, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_stun_2"
name = "Stun_"
trigger = { type = "ability_cast", ability_ids = [3390880975159296] }
duration_secs = 22.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_ball_setup"
name = "Ball Setup"
trigger = { type = "ability_cast", ability_ids = [3390880975159296] }
duration_secs = 27.0
color = [220, 26, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_lightning_ball"
name = "Lightning Ball"
trigger = { type = "timer_expires", timer_id = "master_obai_and_lord_vodd_ball_setup" }
duration_secs = 20.0
color = [220, 26, 188, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_lightning_ball_2"
name = "Lightning Ball_"
trigger = { type = "ability_cast", ability_ids = [3385636820090880] }
duration_secs = 20.0
color = [220, 32, 173, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_force_slash_setup"
name = "Force Slash Setup"
trigger = { type = "ability_cast", ability_ids = [3382269565730816] }
duration_secs = 25.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_force_slash"
name = "Force Slash"
trigger = { type = "timer_expires", timer_id = "master_obai_and_lord_vodd_force_slash_setup" }
duration_secs = 20.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_obai_and_lord_vodd_force_slash_2"
name = "Force Slash_"
trigger = { type = "ability_cast", ability_ids = [3384494358790144] }
duration_secs = 20.0
color = [27, 220, 228, 255]
difficulties = ["veteran", "master"]

# ─── rarrook_and_marko_ka ───
[[boss]]
id = "rarrook_and_marko_ka"
name = "Rarrook and Marko Ka"
difficulties = ["master", "veteran"]
npc_names = ["Rarrook and Marko Ka"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "rarrook_and_marko_ka_shockwave"
name = "Shockwave"
trigger = { type = "ability_cast", ability_ids = [3370432635863040] }
duration_secs = 21.0
color = [220, 32, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_mines"
name = "Mines"
trigger = { type = "ability_cast", ability_ids = [3374568689369088] }
duration_secs = 21.0
color = [213, 199, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_jump_dfa"
name = "Jump + DFA"
trigger = { type = "ability_cast", ability_ids = [3408709384404992] }
duration_secs = 36.0
color = [220, 39, 41, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_stealth_setup"
name = "Stealth Setup"
trigger = { type = "ability_cast", ability_ids = [3406153878863872] }
duration_secs = 15.0
color = [34, 228, 227, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_stealth"
name = "Stealth"
trigger = { type = "timer_expires", timer_id = "rarrook_and_marko_ka_stealth_setup" }
duration_secs = 22.0
color = [31, 208, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_stealth_2"
name = "Stealth_"
trigger = { type = "ability_cast", ability_ids = [3381676860243968] }
duration_secs = 22.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_turrets_setup"
name = "Turrets Setup"
trigger = { type = "ability_cast", ability_ids = [3371536442458112] }
duration_secs = 25.0
color = [97, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_turrets"
name = "Turrets"
trigger = { type = "timer_expires", timer_id = "rarrook_and_marko_ka_turrets_setup" }
duration_secs = 22.0
color = [102, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_turrets_2"
name = "Turrets_"
trigger = { type = "ability_cast", ability_ids = [3381676860243968] }
duration_secs = 22.0
color = [100, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_support_setup"
name = "Support Setup"
trigger = { type = "ability_cast", ability_ids = [3381676860243968] }
duration_secs = 40.0
color = [16, 121, 14, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_support_droids"
name = "Support Droids"
trigger = { type = "timer_expires", timer_id = "rarrook_and_marko_ka_support_setup" }
duration_secs = 22.0
color = [17, 121, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rarrook_and_marko_ka_support_droids_2"
name = "Support Droids_"
trigger = { type = "ability_cast", ability_ids = [3371536442458112] }
duration_secs = 22.0
color = [14, 121, 19, 255]
difficulties = ["veteran", "master"]

# ─── shield_squadron_unit_1 ───
[[boss]]
id = "shield_squadron_unit_1"
name = "Shield Squadron Unit 1"
difficulties = ["master", "veteran"]
npc_names = ["Shield Squadron Unit 1"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "shield_squadron_unit_1_electrical_megastorm"
name = "Electrical Megastorm"
trigger = { type = "ability_cast", ability_ids = [3393835912658944] }
duration_secs = 90.0
color = [32, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_setup"
name = "Missile Setup"
trigger = { type = "ability_cast", ability_ids = [3398719290474496] }
duration_secs = 18.0
color = [220, 37, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_blast"
name = "Missile Blast"
trigger = { type = "timer_expires", timer_id = "shield_squadron_unit_1_missile_setup" }
duration_secs = 22.0
color = [228, 34, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_blast_2"
name = "Missile Blast_"
trigger = { type = "ability_cast", ability_ids = [3395214597160960] }
duration_secs = 22.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds_setup"
name = "Adds Setup"
trigger = { type = "ability_cast", ability_ids = [3395214597160960] }
duration_secs = 62.0
color = [18, 136, 16, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds"
name = "Adds"
trigger = { type = "timer_expires", timer_id = "shield_squadron_unit_1_adds_setup" }
duration_secs = 20.0
color = [21, 128, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [3398719290474496] }
duration_secs = 20.0
color = [15, 128, 17, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_orbital_multistrike"
name = "Orbital Multistrike"
trigger = { type = "ability_cast", ability_ids = [3535453869309952] }
duration_secs = 36.0
color = [220, 98, 32, 255]
difficulties = ["veteran", "master"]
