# Blood Hunt
# 3 boss(es)

[area]
name = "Blood Hunt"
area_id = 833571547775719

# ─── kyramla_gemas_rugam ───
[[boss]]
id = "kyramla_gemas_rugam"
name = "Kyramla Gemas'rugam"
difficulties = ["master", "veteran"]
npc_names = ["Kyramla Gemas'rugam"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kyramla_gemas_rugam_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 255.0
color = [220, 40, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_swipe"
name = "Swipe"
trigger = { type = "ability_cast", ability_ids = [3528062230593536] }
duration_secs = 25.0
color = [228, 121, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash_1st"
name = "Smash 1st"
trigger = { type = "combat_start" }
duration_secs = 27.0
color = [27, 223, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_swipe_adds"
name = "Swipe + Adds"
trigger = { type = "combat_start" }
duration_secs = 17.0
color = [228, 118, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3390988349341696] }
duration_secs = 29.0
color = [27, 151, 43, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash_ends"
name = "Smash Ends"
trigger = { type = "ability_cast", ability_ids = [3528066525560832] }
duration_secs = 9.0
color = [32, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash"
name = "Smash"
trigger = { type = "timer_expires", timer_id = "kyramla_gemas_rugam_smash_ends" }
duration_secs = 19.5
color = [32, 220, 210, 255]
difficulties = ["veteran", "master"]

# ─── shae_vizla ───
[[boss]]
id = "shae_vizla"
name = "Shae Vizla"
difficulties = ["master", "veteran"]
npc_names = ["Shae Vizla"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "shae_vizla_death_from_above"
name = "Death from Above"
trigger = { type = "ability_cast", ability_ids = [3411672911839232] }
duration_secs = 15.0
color = [220, 32, 147, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_grapple_droid"
name = "Grapple Droid"
trigger = { type = "timer_expires", timer_id = "67da8876-8e7e-43fe-b0e6-6f29266f2c65" }
duration_secs = 45.0
color = [228, 141, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_maelstrom"
name = "Maelstrom"
trigger = { type = "timer_expires", timer_id = "shae_vizla_grapple_droid" }
duration_secs = 15.0
color = [213, 125, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_electro_dart_setup"
name = "Electro Dart Setup"
trigger = { type = "ability_cast", ability_ids = [3408391556825088] }
duration_secs = 20.0
color = [206, 213, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_electro_dart"
name = "Electro Dart"
trigger = { type = "timer_expires", timer_id = "shae_vizla_electro_dart_setup" }
duration_secs = 10.0
color = [209, 213, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_electro_dart_2"
name = "Electro Dart_"
trigger = { type = "ability_cast", ability_ids = [3408374376955904] }
duration_secs = 10.0
color = [205, 195, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_carbonize_setup"
name = "Carbonize Setup"
trigger = { type = "ability_cast", ability_ids = [3408374376955904] }
duration_secs = 20.0
color = [32, 212, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_carbonize"
name = "Carbonize"
trigger = { type = "timer_expires", timer_id = "shae_vizla_carbonize_setup" }
duration_secs = 10.0
color = [38, 209, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_carbonize_2"
name = "Carbonize_"
trigger = { type = "ability_cast", ability_ids = [3408391556825088] }
duration_secs = 10.0
color = [46, 216, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shae_vizla_can_t_stun"
name = "Can't stun"
trigger = { type = "ability_cast", ability_ids = [3408387261857792] }
duration_secs = 10.0
color = [13, 151, 14, 255]
difficulties = ["veteran", "master"]

# ─── valk_jos ───
[[boss]]
id = "valk_jos"
name = "Valk & Jos"
difficulties = ["master", "veteran"]
npc_names = ["Valk & Jos"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "valk_jos_jet_charge"
name = "Jet Charge"
trigger = { type = "ability_cast", ability_ids = [3395794417745920] }
duration_secs = 30.0
color = [228, 122, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valk_jos_aerial_strike"
name = "Aerial Strike"
trigger = { type = "ability_cast", ability_ids = [3394445798014976] }
duration_secs = 33.0
color = [220, 36, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valk_jos_missiles"
name = "Missiles"
trigger = { type = "ability_cast", ability_ids = [3395824482516992] }
duration_secs = 10.5
color = [213, 203, 25, 255]
difficulties = ["veteran", "master"]
