# Boarding Party
# 3 boss(es)

[area]
name = "Boarding Party"
area_id = 833571547775680

# ─── chief_engineer_kels ───
[[boss]]
id = "chief_engineer_kels"
name = "Chief Engineer Kels"
difficulties = ["master", "veteran"]
npc_names = ["Chief Engineer Kels"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "chief_engineer_kels_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 105.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "chief_engineer_kels_reflective_shield"
name = "Reflective Shield"
trigger = { type = "ability_cast", ability_ids = [2541542602440704] }
duration_secs = 30.0
color = [32, 208, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "chief_engineer_kels_reactor_pulse"
name = "Reactor Pulse"
trigger = { type = "ability_cast", ability_ids = [2535314899861504] }
duration_secs = 5.0
color = [220, 113, 26, 255]
difficulties = ["veteran", "master"]

# ─── hxi_54_juggernaut ───
[[boss]]
id = "hxi_54_juggernaut"
name = "HXI-54 Juggernaut"
difficulties = ["master", "veteran"]
npc_names = ["HXI-54 Juggernaut"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "hxi_54_juggernaut_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 100.0
color = [205, 30, 37, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hxi_54_juggernaut_generator_drain"
name = "Generator Drain"
trigger = { type = "ability_cast", ability_ids = [2304219889532928] }
duration_secs = 33.0
color = [26, 217, 220, 255]
difficulties = ["veteran", "master"]

# ─── officer_trio ───
[[boss]]
id = "officer_trio"
name = "Officer Trio"
difficulties = ["master", "veteran"]
npc_names = ["Officer Trio"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "officer_trio_restorative_scan"
name = "Restorative Scan"
trigger = { type = "ability_cast", ability_ids = [2520900989616128] }
duration_secs = 20.0
color = [8, 136, 22, 255]
difficulties = ["veteran", "master"]
