# Cademimu
# 4 boss(es)

[area]
name = "Cademimu"
area_id = 833571547775684

# ─── captain_grimyk ───
[[boss]]
id = "captain_grimyk"
name = "Captain Grimyk"
difficulties = ["master", "veteran"]
npc_names = ["Captain Grimyk"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "captain_grimyk_grenade"
name = "Grenade"
trigger = { type = "ability_cast", ability_ids = [2506302395777024] }
duration_secs = 15.0
color = [167, 158, 15, 255]
difficulties = ["veteran", "master"]

# ─── garold_the_dark_one ───
[[boss]]
id = "garold_the_dark_one"
name = "Garold the Dark One"
difficulties = ["master", "veteran"]
npc_names = ["Garold the Dark One"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "garold_the_dark_one_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 240.0
color = [228, 45, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "garold_the_dark_one_pull_storm"
name = "Pull + Storm"
trigger = { type = "ability_cast", ability_ids = [2520518737526784] }
duration_secs = 30.0
color = [144, 27, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "garold_the_dark_one_pull_storm_2"
name = "Pull + Storm_"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [147, 32, 220, 255]
difficulties = ["veteran", "master"]

# ─── general_ortol ───
[[boss]]
id = "general_ortol"
name = "General Ortol"
difficulties = ["master", "veteran"]
npc_names = ["General Ortol"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "general_ortol_root"
name = "Root"
trigger = { type = "ability_cast", ability_ids = [2506624518324224] }
duration_secs = 15.0
color = [39, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_knocback"
name = "Knocback"
trigger = { type = "ability_cast", ability_ids = [2694782740594688] }
duration_secs = 15.0
color = [220, 122, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_single_rocket"
name = "Single Rocket"
trigger = { type = "ability_cast", ability_ids = [3213541775507456] }
duration_secs = 30.0
color = [208, 220, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_multi_rocket"
name = "Multi Rocket"
trigger = { type = "ability_cast", ability_ids = [3213546070474752] }
duration_secs = 30.0
color = [213, 194, 31, 255]
difficulties = ["veteran", "master"]

# ─── officer_xander ───
[[boss]]
id = "officer_xander"
name = "Officer Xander"
difficulties = ["master", "veteran"]
npc_names = ["Officer Xander"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "officer_xander_droid_activation"
name = "Droid Activation_"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [9, 151, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "officer_xander_droid_activation_2"
name = "Droid Activation"
trigger = { type = "ability_cast", ability_ids = [3230876263514112] }
duration_secs = 45.0
color = [22, 151, 36, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "officer_xander_sticky_grenade"
name = "Sticky Grenade"
trigger = { type = "ability_cast", ability_ids = [3232955027685376] }
duration_secs = 15.0
color = [182, 180, 16, 255]
difficulties = ["veteran", "master"]
