# Crisis on Umbara
# 4 boss(es)

[area]
name = "Crisis on Umbara"
area_id = 833571547775775

# ─── alpha_slybex ───
[[boss]]
id = "alpha_slybex"
name = "Alpha Slybex"
difficulties = ["master", "veteran"]
npc_names = ["Alpha Slybex"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "alpha_slybex_poison_breath"
name = "Poison Breath"
trigger = { type = "ability_cast", ability_ids = [4129623940005888] }
duration_secs = 30.0
color = [17, 144, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "alpha_slybex_pounce"
name = "Pounce"
trigger = { type = "ability_cast", ability_ids = [4121394782666752] }
duration_secs = 30.0
color = [220, 19, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "alpha_slybex_target_swap"
name = "Target Swap"
trigger = { type = "ability_cast", ability_ids = [4121652480704512] }
duration_secs = 30.0
color = [31, 208, 213, 255]
difficulties = ["veteran", "master"]

# ─── technician_canni_elli_vaa ───
[[boss]]
id = "technician_canni_elli_vaa"
name = "Technician Canni & Elli-Vaa"
difficulties = ["master", "veteran"]
npc_names = ["Technician Canni & Elli-Vaa"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "technician_canni_elli_vaa_stealth"
name = "Stealth"
trigger = { type = "ability_cast", ability_ids = [4122318200635392] }
duration_secs = 15.0
color = [34, 220, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "technician_canni_elli_vaa_phase_2_end"
name = "Phase 2 end"
trigger = { type = "timer_expires", timer_id = "6871bf82-9b61-4c88-a251-c529f1e3c03b" }
duration_secs = 30.0
color = [220, 42, 32, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "technician_canni_elli_vaa_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [4122305315733504] }
duration_secs = 13.5
color = [220, 41, 32, 255]
difficulties = ["veteran", "master"]

# ─── umbaran_spider_tank ───
[[boss]]
id = "umbaran_spider_tank"
name = "Umbaran Spider Tank"
difficulties = ["master", "veteran"]
npc_names = ["Umbaran Spider Tank"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "umbaran_spider_tank_phase_1"
name = "Phase 1"
trigger = { type = "timer_expires", timer_id = "29b68187-ddc8-4b44-a95f-1842e8085fe2" }
duration_secs = 25.0
color = [20, 136, 21, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "umbaran_spider_tank_concussive_blast"
name = "Concussive Blast"
trigger = { type = "ability_cast", ability_ids = [4126385534664704] }
duration_secs = 14.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "umbaran_spider_tank_proximity_burner"
name = "Proximity Burner"
trigger = { type = "ability_cast", ability_ids = [4117963103797248] }
duration_secs = 12.0
color = [220, 104, 19, 255]
difficulties = ["veteran", "master"]

# ─── vixian_mauler ───
[[boss]]
id = "vixian_mauler"
name = "Vixian Mauler"
difficulties = ["master", "veteran"]
npc_names = ["Vixian Mauler"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "vixian_mauler_ground_pound"
name = "Ground Pound"
trigger = { type = "ability_cast", ability_ids = [4116970966351872] }
duration_secs = 12.0
color = [228, 27, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vixian_mauler_fierce_swipe"
name = "Fierce Swipe"
trigger = { type = "ability_cast", ability_ids = [4116983851253760] }
duration_secs = 15.0
color = [220, 114, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vixian_mauler_enraged_pounding"
name = "Enraged Pounding"
trigger = { type = "ability_cast", ability_ids = [4117353218441216] }
duration_secs = 9.0
color = [213, 40, 31, 255]
difficulties = ["veteran", "master"]
