# Czerka Corporate Labs
# 3 boss(es)

[area]
name = "Czerka Corporate Labs"
area_id = 137438993332

# ─── chief_zokar ───
[[boss]]
id = "chief_zokar"
name = "Chief Zokar"
difficulties = ["master", "veteran"]
npc_names = ["Chief Zokar"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "chief_zokar_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 360.0
color = [220, 38, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "chief_zokar_jump"
name = "Jump"
trigger = { type = "ability_cast", ability_ids = [3258385529044992] }
duration_secs = 30.0
color = [31, 213, 210, 255]
difficulties = ["veteran", "master"]

# ─── cz_8x_eradicator_droid ───
[[boss]]
id = "cz_8x_eradicator_droid"
name = "CZ-8X Eradicator Droid"
difficulties = ["master", "veteran"]
npc_names = ["CZ-8X Eradicator Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "cz_8x_eradicator_droid_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 360.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "cz_8x_eradicator_droid_charged_plating"
name = "Charged Plating"
trigger = { type = "ability_cast", ability_ids = [3256671837093888] }
duration_secs = 32.0
color = [220, 127, 32, 255]
difficulties = ["veteran", "master"]

# ─── rasmus_blys ───
[[boss]]
id = "rasmus_blys"
name = "Rasmus Blys"
difficulties = ["master", "veteran"]
npc_names = ["Rasmus Blys"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "rasmus_blys_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 360.0
color = [213, 19, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rasmus_blys_escape"
name = "Escape"
trigger = { type = "ability_cast", ability_ids = [3271223186292736] }
duration_secs = 45.0
color = [38, 51, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rasmus_blys_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3258449953554432] }
duration_secs = 30.0
color = [34, 144, 26, 255]
difficulties = ["veteran", "master"]
