# Czerka Core Meltdown
# 3 boss(es)

[area]
name = "Czerka Core Meltdown"
area_id = 137438993342

# ─── enhanced_duneclaw ───
[[boss]]
id = "enhanced_duneclaw"
name = "Enhanced Duneclaw"
difficulties = ["master", "veteran"]
npc_names = ["Enhanced Duneclaw"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "enhanced_duneclaw_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 360.0
color = [213, 22, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "enhanced_duneclaw_sandstorm"
name = "Sandstorm"
trigger = { type = "ability_cast", ability_ids = [3262049136148480] }
duration_secs = 60.0
color = [213, 108, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "enhanced_duneclaw_sweep"
name = "Sweep"
trigger = { type = "ability_cast", ability_ids = [3261555214909440] }
duration_secs = 12.0
color = [38, 203, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "enhanced_duneclaw_rampage"
name = "Rampage"
trigger = { type = "ability_cast", ability_ids = [3284563354714112] }
duration_secs = 12.0
color = [220, 196, 26, 255]
difficulties = ["veteran", "master"]

# ─── enhanced_vrblther ───
[[boss]]
id = "enhanced_vrblther"
name = "Enhanced Vrblther"
difficulties = ["master", "veteran"]
npc_names = ["Enhanced Vrblther"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "enhanced_vrblther_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 360.0
color = [228, 44, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "enhanced_vrblther_lift"
name = "Lift"
trigger = { type = "ability_cast", ability_ids = [3261890222358528] }
duration_secs = 10.0
color = [228, 39, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "enhanced_vrblther_smash"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [3261898812293120] }
duration_secs = 15.0
color = [32, 141, 220, 255]
difficulties = ["veteran", "master"]

# ─── the_vigilant ───
[[boss]]
id = "the_vigilant"
name = "The Vigilant"
difficulties = ["master", "veteran"]
npc_names = ["The Vigilant"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_vigilant_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 480.0
color = [220, 42, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [3286667888689152] }
duration_secs = 12.0
color = [34, 222, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_beam"
name = "Beam"
trigger = { type = "ability_cast", ability_ids = [3264020526137344] }
duration_secs = 10.0
color = [194, 220, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_backhand"
name = "Backhand"
trigger = { type = "ability_cast", ability_ids = [3263689813655552] }
duration_secs = 10.0
color = [228, 127, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_slash"
name = "Slash"
trigger = { type = "ability_cast", ability_ids = [3263951806660608] }
duration_secs = 12.0
color = [213, 38, 163, 255]
difficulties = ["veteran", "master"]
