# Hammer Station
# 4 boss(es)

[area]
name = "Hammer Station"
area_id = 833571547775682

# ─── asteroid_beast ───
[[boss]]
id = "asteroid_beast"
name = "Asteroid Beast"
difficulties = ["master", "veteran"]
npc_names = ["Asteroid Beast"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "asteroid_beast_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 210.0
color = [220, 28, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "asteroid_beast_kick_sweep"
name = "Kick + Sweep"
trigger = { type = "ability_cast", ability_ids = [3251041134968832] }
duration_secs = 20.0
color = [220, 130, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "asteroid_beast_rampage"
name = "Rampage"
trigger = { type = "ability_cast", ability_ids = [3251036840001536] }
duration_secs = 21.0
color = [39, 217, 220, 255]
difficulties = ["veteran", "master"]

# ─── battlelord_kreshan ───
[[boss]]
id = "battlelord_kreshan"
name = "Battlelord Kreshan"
difficulties = ["master", "veteran"]
npc_names = ["Battlelord Kreshan"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "battlelord_kreshan_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [2291077289607168] }
duration_secs = 18.0
color = [174, 173, 5, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "battlelord_kreshan_sweeping_gunfire"
name = "Sweeping Gunfire"
trigger = { type = "ability_cast", ability_ids = [2291098764443648] }
duration_secs = 12.0
color = [220, 34, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "battlelord_kreshan_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [2276560300146688] }
duration_secs = 30.0
color = [15, 174, 41, 255]
difficulties = ["veteran", "master"]

# ─── dn_314_tunneler ───
[[boss]]
id = "dn_314_tunneler"
name = "DN-314 Tunneler"
difficulties = ["master", "veteran"]
npc_names = ["DN-314 Tunneler"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "dn_314_tunneler_targeted_laser"
name = "Targeted Laser"
trigger = { type = "ability_cast", ability_ids = [3169647209742336] }
duration_secs = 21.0
color = [228, 121, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_1"
name = "Adds 1"
trigger = { type = "ability_cast", ability_ids = [3163939198205952] }
duration_secs = 10.0
color = [20, 174, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_2"
name = "Adds 2"
trigger = { type = "timer_expires", timer_id = "dn_314_tunneler_adds_1" }
duration_secs = 10.0
color = [16, 182, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_3"
name = "Adds 3"
trigger = { type = "timer_expires", timer_id = "dn_314_tunneler_adds_2" }
duration_secs = 10.0
color = [20, 174, 46, 255]
difficulties = ["veteran", "master"]

# ─── vorgan_the_volcano ───
[[boss]]
id = "vorgan_the_volcano"
name = "Vorgan the Volcano"
difficulties = ["master"]
npc_names = ["Vorgan the Volcano"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "vorgan_the_volcano_shield_1st"
name = "Shield 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [27, 228, 223, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shield_self"
name = "Shield Self"
trigger = { type = "ability_cast", ability_ids = [3230060219727872] }
duration_secs = 45.0
color = [32, 220, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shielf_friends"
name = "Shielf Friends"
trigger = { type = "ability_cast", ability_ids = [3230068809662464] }
duration_secs = 60.0
color = [28, 20, 228, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shield_active"
name = "Shield Active"
trigger = { type = "ability_cast", ability_ids = [3230060219727872] }
duration_secs = 20.0
color = [220, 39, 32, 255]
difficulties = ["master"]
