# Kaon Under Siege
# 1 boss(es)

[area]
name = "Kaon Under Siege"
area_id = 833571547775674

# ─── rakghoul_behemoth ───
[[boss]]
id = "rakghoul_behemoth"
name = "Rakghoul Behemoth"
difficulties = ["master", "veteran"]
npc_names = ["Rakghoul Behemoth"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "rakghoul_behemoth_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 180.0
color = [220, 48, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rakghoul_behemoth_smash"
name = "Smash_"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [44, 209, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rakghoul_behemoth_smash_2"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [2765327578431488] }
duration_secs = 15.0
color = [31, 202, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "rakghoul_behemoth_lift"
name = "Lift"
trigger = { type = "ability_cast", ability_ids = [2765336168366080] }
duration_secs = 10.0
color = [212, 220, 32, 255]
difficulties = ["veteran", "master"]
