# Korriban Incursion
# 4 boss(es)

[area]
name = "Korriban Incursion"
area_id = 833571547775710

# ─── commander_jensyn ───
[[boss]]
id = "commander_jensyn"
name = "Commander Jensyn"
difficulties = ["master", "veteran"]
npc_names = ["Commander Jensyn"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_jensyn_master_strike"
name = "Master Strike_"
trigger = { type = "ability_cast", ability_ids = [3333800859795456] }
duration_secs = 7.0
color = [32, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_reflect_permision"
name = "Reflect Permision"
trigger = { type = "ability_cast", ability_ids = [3334715687829504] }
duration_secs = 16.0
color = [186, 197, 23, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_stun_add"
name = "Stun Add"
trigger = { type = "timer_expires", timer_id = "commander_jensyn_reflect_permision" }
duration_secs = 44.0
color = [19, 121, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_setup"
name = "Suicide Add Setup"
trigger = { type = "ability_cast", ability_ids = [3486143349784576] }
duration_secs = 5.0
color = [228, 137, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add"
name = "Suicide Add"
trigger = { type = "timer_expires", timer_id = "commander_jensyn_suicide_add_setup" }
duration_secs = 10.0
color = [220, 138, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_2"
name = "Suicide Add_"
trigger = { type = "ability_cast", ability_ids = [3332641218625536] }
duration_secs = 10.0
color = [228, 138, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_3"
name = "Suicide Add__"
trigger = { type = "effect_removed", effect_ids = [3334857421750272] }
duration_secs = 10.0
color = [220, 125, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_master_strike_2"
name = "Master Strike"
trigger = { type = "ability_cast", ability_ids = [3333289758687232] }
duration_secs = 15.0
color = [27, 208, 228, 255]
difficulties = ["veteran", "master"]

# ─── master_riilna ───
[[boss]]
id = "master_riilna"
name = "Master Riilna"
difficulties = ["master", "veteran"]
npc_names = ["Master Riilna"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_riilna_quake"
name = "Quake"
trigger = { type = "ability_cast", ability_ids = [3342210405761024] }
duration_secs = 30.0
color = [220, 216, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_riilna_knocback"
name = "Knocback"
trigger = { type = "ability_cast", ability_ids = [3483446110322688] }
duration_secs = 13.5
color = [228, 35, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_riilna_mind_crush"
name = "Mind Crush"
trigger = { type = "ability_cast", ability_ids = [3342300600074240] }
duration_secs = 12.0
color = [147, 31, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_riilna_throw"
name = "Throw"
trigger = { type = "ability_cast", ability_ids = [3342197520859136] }
duration_secs = 20.0
color = [228, 112, 20, 255]
difficulties = ["veteran", "master"]

# ─── r_9xr ───
[[boss]]
id = "r_9xr"
name = "R-9XR"
difficulties = ["master", "veteran"]
npc_names = ["R-9XR"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "r_9xr_extermination_mode"
name = "Extermination Mode"
trigger = { type = "combat_start" }
duration_secs = 135.0
color = [213, 25, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r_9xr_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3483824067444736] }
duration_secs = 30.0
color = [25, 136, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r_9xr_adds_2"
name = "Adds_"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [8, 144, 13, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r_9xr_laser_burst"
name = "Laser Burst"
trigger = { type = "ability_cast", ability_ids = [3330704188375040] }
duration_secs = 16.5
color = [26, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r_9xr_missiels"
name = "Missiels"
trigger = { type = "ability_cast", ability_ids = [3330712778309632] }
duration_secs = 30.0
color = [213, 130, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r_9xr_missiles"
name = "Missiles_"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [220, 126, 32, 255]
difficulties = ["veteran", "master"]

# ─── republic_commander ───
[[boss]]
id = "republic_commander"
name = "Republic Commander"
difficulties = ["master", "veteran"]
npc_names = ["Republic Commander"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "republic_commander_force_push"
name = "Force Push"
trigger = { type = "ability_cast", ability_ids = [3493260110594048] }
duration_secs = 10.0
color = [192, 27, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_master_strike"
name = "Master Strike"
trigger = { type = "ability_cast", ability_ids = [3493272995495936] }
duration_secs = 30.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_master_stasis"
name = "Master Stasis"
trigger = { type = "ability_cast", ability_ids = [3493247225692160] }
duration_secs = 32.0
color = [31, 202, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_shockwave"
name = "Shockwave"
trigger = { type = "ability_cast", ability_ids = [811976452210688] }
duration_secs = 30.0
color = [213, 201, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_hilt_strike"
name = "Hilt Strike"
trigger = { type = "ability_cast", ability_ids = [3493277290463232] }
duration_secs = 30.0
color = [220, 128, 39, 255]
difficulties = ["veteran", "master"]
