# Lost Island
# 4 boss(es)

[area]
name = "Lost Island"
area_id = 833571547775675

# ─── doctor_lorrick ───
[[boss]]
id = "doctor_lorrick"
name = "Doctor Lorrick"
difficulties = ["master", "veteran"]
npc_names = ["Doctor Lorrick"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "doctor_lorrick_bash"
name = "Bash"
trigger = { type = "ability_cast", ability_ids = [2877482059431936] }
duration_secs = 12.0
color = [220, 29, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "doctor_lorrick_ravage"
name = "Ravage"
trigger = { type = "ability_cast", ability_ids = [2877451994660864] }
duration_secs = 12.0
color = [220, 19, 26, 255]
difficulties = ["veteran", "master"]

# ─── lr_5_sentinel_droid ───
[[boss]]
id = "lr_5_sentinel_droid"
name = "LR-5 Sentinel Droid"
difficulties = ["master", "veteran"]
npc_names = ["LR-5 Sentinel Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "lr_5_sentinel_droid_incinerate"
name = "Incinerate"
trigger = { type = "ability_cast", ability_ids = [2851183974678528] }
duration_secs = 17.5
color = [220, 113, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 255.0
color = [220, 37, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge_1st"
name = "Discharge 1st"
trigger = { type = "combat_start" }
duration_secs = 19.0
color = [32, 204, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge"
name = "Discharge_"
trigger = { type = "timer_expires", timer_id = "lr_5_sentinel_droid_discharge_2" }
duration_secs = 20.0
color = [32, 208, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge_2"
name = "Discharge"
trigger = { type = "timer_expires", timer_id = "lr_5_sentinel_droid_discharge_1st" }
duration_secs = 20.0
color = [38, 213, 212, 255]
difficulties = ["veteran", "master"]

# ─── project_sav_rak ───
[[boss]]
id = "project_sav_rak"
name = "Project Sav-Rak"
difficulties = ["master", "veteran"]
npc_names = ["Project Sav-Rak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "project_sav_rak_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 280.0
color = [220, 33, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "project_sav_rak_smash"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [2837543158546432] }
duration_secs = 24.0
color = [220, 104, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "project_sav_rak_smash_2"
name = "Smash_"
trigger = { type = "combat_start" }
duration_secs = 12.0
color = [220, 97, 32, 255]
difficulties = ["veteran", "master"]

# ─── transgenic_sample_eleven ───
[[boss]]
id = "transgenic_sample_eleven"
name = "Transgenic Sample Eleven"
difficulties = ["master", "veteran"]
npc_names = ["Transgenic Sample Eleven"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "transgenic_sample_eleven_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 145.0
color = [220, 35, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "transgenic_sample_eleven_frostbite"
name = "Frostbite"
trigger = { type = "ability_cast", ability_ids = [2877645268189184] }
duration_secs = 45.0
color = [39, 207, 220, 255]
difficulties = ["veteran", "master"]
