# Mandalorian Raiders
# 3 boss(es)

[area]
name = "Mandalorian Raiders"
area_id = 833571547775687

# ─── braxx_the_bloodhound ───
[[boss]]
id = "braxx_the_bloodhound"
name = "Braxx the Bloodhound"
difficulties = ["master", "veteran"]
npc_names = ["Braxx the Bloodhound"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "braxx_the_bloodhound_carbonize"
name = "Carbonize"
trigger = { type = "ability_cast", ability_ids = [2463666255429632] }
duration_secs = 20.0
color = [27, 228, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "braxx_the_bloodhound_carbonize_2"
name = "Carbonize_"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [27, 228, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "braxx_the_bloodhound_inspire_end"
name = "Inspire End"
trigger = { type = "ability_cast", ability_ids = [2439519949291520] }
duration_secs = 15.0
color = [220, 34, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "braxx_the_bloodhound_inspire"
name = "Inspire"
trigger = { type = "timer_expires", timer_id = "braxx_the_bloodhound_inspire_end" }
duration_secs = 15.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

# ─── gil ───
[[boss]]
id = "gil"
name = "Gil"
difficulties = ["master"]
npc_names = ["Gil"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gil_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 210.0
color = [220, 31, 26, 255]
difficulties = ["master"]

[[boss.timer]]
id = "gil_jump_ww"
name = "Jump + WW"
trigger = { type = "ability_cast", ability_ids = [3250963825557504] }
duration_secs = 20.0
color = [189, 72, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "gil_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [3250972415492096] }
duration_secs = 12.0
color = [40, 228, 224, 255]
difficulties = ["master"]

# ─── mavrix_varad ───
[[boss]]
id = "mavrix_varad"
name = "Mavrix Varad"
difficulties = ["master", "veteran"]
npc_names = ["Mavrix Varad"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "mavrix_varad_random_missile_vm"
name = "Random Missile VM"
trigger = { type = "ability_cast", ability_ids = [2455797875343360] }
duration_secs = 10.0
color = [220, 124, 32, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "mavrix_varad_random_missile_mm"
name = "Random Missile MM"
trigger = { type = "ability_cast", ability_ids = [2455797875343360] }
duration_secs = 18.0
color = [220, 120, 32, 255]
difficulties = ["master"]
