# Objective Meridian
# 4 boss(es)

[area]
name = "Objective Meridian"
area_id = 833571547775793

# ─── commander_rasha ───
[[boss]]
id = "commander_rasha"
name = "Commander Rasha"
difficulties = ["master", "veteran"]
npc_names = ["Commander Rasha"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_rasha_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4282928502669312] }
duration_secs = 45.0
color = [12, 136, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [4284040899198976] }
duration_secs = 45.0
color = [22, 136, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_shield"
name = "Shield"
trigger = { type = "ability_cast", ability_ids = [4283924935081984] }
duration_secs = 28.0
color = [38, 203, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_artillery"
name = "Artillery"
trigger = { type = "ability_cast", ability_ids = [4282919912734720] }
duration_secs = 23.0
color = [220, 35, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_sweeping_gunfire"
name = "Sweeping Gunfire"
trigger = { type = "ability_cast", ability_ids = [4282954272473088] }
duration_secs = 15.0
color = [213, 113, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_piercing_rounds"
name = "Piercing Rounds"
trigger = { type = "ability_cast", ability_ids = [4282958567440384] }
duration_secs = 20.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]

# ─── master_jakir_seldin ───
[[boss]]
id = "master_jakir_seldin"
name = "Master Jakir & Seldin"
difficulties = ["master", "veteran"]
npc_names = ["Master Jakir & Seldin"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_jakir_seldin_weakness"
name = "Weakness"
trigger = { type = "ability_cast", ability_ids = [4267470915371008] }
duration_secs = 20.0
color = [26, 220, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_serenity"
name = "Serenity"
trigger = { type = "ability_cast", ability_ids = [4271160292278272] }
duration_secs = 40.0
color = [20, 136, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_force_barrage"
name = "Force Barrage"
trigger = { type = "ability_cast", ability_ids = [4270885414371328] }
duration_secs = 12.0
color = [228, 110, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_force_slam"
name = "Force Slam"
trigger = { type = "ability_cast", ability_ids = [4275025762844672] }
duration_secs = 20.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_weakness_2"
name = "Weakness_"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [39, 214, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_serentiy"
name = "Serentiy"
trigger = { type = "timer_expires", timer_id = "master_jakir_seldin_weakness_2" }
duration_secs = 5.0
color = [11, 128, 15, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_sweeping_slash"
name = "Sweeping Slash"
trigger = { type = "ability_cast", ability_ids = [4271310616133632] }
duration_secs = 15.0
color = [220, 32, 169, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_jakir_seldin_healing_trance"
name = "Healing Trance"
trigger = { type = "ability_cast", ability_ids = [4271417990316032] }
duration_secs = 30.0
color = [213, 201, 31, 255]
difficulties = ["veteran", "master"]

# ─── r10_x6 ───
[[boss]]
id = "r10_x6"
name = "R10-X6"
difficulties = ["master", "veteran"]
npc_names = ["R10-X6"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "r10_x6_mines"
name = "Mines"
trigger = { type = "ability_cast", ability_ids = [4267475210338304] }
duration_secs = 30.0
color = [17, 113, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r10_x6_explosive_shot"
name = "Explosive Shot"
trigger = { type = "ability_cast", ability_ids = [4270069370585088] }
duration_secs = 18.0
color = [220, 40, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r10_x6_explosive_shot_2"
name = "Explosive Shot_"
trigger = { type = "ability_cast", ability_ids = [4361857116667904] }
duration_secs = 16.0
color = [220, 26, 26, 255]
difficulties = ["veteran", "master"]

# ─── tau_idair ───
[[boss]]
id = "tau_idair"
name = "Tau Idair"
difficulties = ["master", "veteran"]
npc_names = ["Tau Idair"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "tau_idair_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4295542821617664] }
duration_secs = 40.0
color = [19, 136, 16, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_blade_storm"
name = "Blade Storm"
trigger = { type = "ability_cast", ability_ids = [4307856492855296] }
duration_secs = 31.0
color = [220, 33, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_master_strike"
name = "Master Strike"
trigger = { type = "ability_cast", ability_ids = [4292858467057664] }
duration_secs = 30.0
color = [220, 43, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_forcequake"
name = "Forcequake"
trigger = { type = "timer_expires", timer_id = "5a9c909e-81c0-49c3-85aa-ead7beae3fc8" }
duration_secs = 12.0
color = [220, 176, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [4337350033276928] }
duration_secs = 40.0
color = [17, 144, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_adds_1st"
name = "Adds 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [15, 128, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "tau_idair_breath_of_ossus"
name = "Breath of Ossus"
trigger = { type = "timer_expires", timer_id = "0db4bddd-50e4-48fa-bbed-a9174e8a7d7c" }
duration_secs = 10.0
color = [100, 232, 237, 255]
difficulties = ["veteran", "master"]
