# Ruins of Nul
# 3 boss(es)

[area]
name = "Ruins of Nul"
area_id = 833571547775798

# ─── apex_ranphyx ───
[[boss]]
id = "apex_ranphyx"
name = "Apex Ranphyx"
difficulties = ["master", "veteran"]
npc_names = ["Apex Ranphyx"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "apex_ranphyx_harrowing"
name = "Harrowing"
trigger = { type = "ability_cast", ability_ids = [4474780396814336] }
duration_secs = 20.0
color = [220, 43, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "apex_ranphyx_roar"
name = "Roar"
trigger = { type = "ability_cast", ability_ids = [4484667411529728] }
duration_secs = 21.0
color = [220, 30, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "apex_ranphyx_feral_pounce"
name = "Feral Pounce"
trigger = { type = "ability_cast", ability_ids = [4473539151265792] }
duration_secs = 32.0
color = [220, 126, 39, 255]
difficulties = ["veteran", "master"]

# ─── droid_squad ───
[[boss]]
id = "droid_squad"
name = "Droid Squad"
difficulties = ["master", "veteran"]
npc_names = ["Droid Squad"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "droid_squad_hit_floaty"
name = "Hit floaty"
trigger = { type = "ability_cast", ability_ids = [4567908172693504] }
duration_secs = 12.0
color = [228, 46, 34, 255]
difficulties = ["veteran", "master"]

# ─── regnant ───
[[boss]]
id = "regnant"
name = "Regnant"
difficulties = ["master", "veteran"]
npc_names = ["Regnant"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "regnant_middle_beam"
name = "Middle Beam"
trigger = { type = "ability_cast", ability_ids = [4526972839395328] }
duration_secs = 12.0
color = [228, 199, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "regnant_multi_beams_end"
name = "Multi Beams End"
trigger = { type = "ability_cast", ability_ids = [4482172035530752] }
duration_secs = 21.5
color = [228, 30, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "regnant_multi_beams"
name = "Multi Beams"
trigger = { type = "timer_expires", timer_id = "regnant_multi_beams_end" }
duration_secs = 15.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "regnant_missile_barrage_end"
name = "Missile Barrage End"
trigger = { type = "ability_cast", ability_ids = [4578800209756160] }
duration_secs = 21.5
color = [220, 113, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "regnant_missile_barrage"
name = "Missile Barrage"
trigger = { type = "timer_expires", timer_id = "regnant_missile_barrage_end" }
duration_secs = 20.0
color = [220, 124, 32, 255]
difficulties = ["veteran", "master"]
