# Secrets of the Enclave
# 4 boss(es)

[area]
name = "Secrets of the Enclave"
area_id = 833571547775786

# ─── graul ───
[[boss]]
id = "graul"
name = "Graul"
difficulties = ["master", "veteran"]
npc_names = ["Graul"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "graul_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4447455814877184] }
duration_secs = 30.0
color = [12, 136, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_slam"
name = "Slam"
trigger = { type = "ability_cast", ability_ids = [4450183119110144] }
duration_secs = 15.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_quaking_blows_mm"
name = "Quaking Blows MM"
trigger = { type = "ability_cast", ability_ids = [4456380756918272] }
duration_secs = 30.0
color = [228, 98, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_quaking_blows"
name = "Quaking Blows"
trigger = { type = "ability_cast", ability_ids = [4447460109844480] }
duration_secs = 30.0
color = [228, 217, 34, 255]
difficulties = ["veteran", "master"]

# ─── master_leeha_narezz ───
[[boss]]
id = "master_leeha_narezz"
name = "Master Leeha Narezz"
difficulties = ["master", "veteran"]
npc_names = ["Master Leeha Narezz"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_leeha_narezz_center_jump"
name = "Center Jump"
trigger = { type = "ability_cast", ability_ids = [4448658405720064] }
duration_secs = 15.0
color = [211, 213, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_forcequake"
name = "Forcequake"
trigger = { type = "ability_cast", ability_ids = [4451158076686336] }
duration_secs = 45.0
color = [220, 41, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4458154578411520] }
duration_secs = 23.0
color = [213, 117, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4448714240294912] }
duration_secs = 16.0
color = [14, 121, 22, 255]
difficulties = ["veteran", "master"]

# ─── monstrous_terentatek ───
[[boss]]
id = "monstrous_terentatek"
name = "Monstrous Terentatek"
difficulties = ["master", "veteran"]
npc_names = ["Monstrous Terentatek"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "monstrous_terentatek_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4458077269000192] }
duration_secs = 45.0
color = [20, 136, 33, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "monstrous_terentatek_brutal_leap"
name = "Brutal Leap"
trigger = { type = "ability_cast", ability_ids = [4449727852576768] }
duration_secs = 15.0
color = [228, 130, 27, 255]
difficulties = ["veteran", "master"]

# ─── republic_squad ───
[[boss]]
id = "republic_squad"
name = "Republic Squad"
difficulties = ["master", "veteran"]
npc_names = ["Republic Squad"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "republic_squad_jump"
name = "Jump"
trigger = { type = "ability_cast", ability_ids = [4450986277994496] }
duration_secs = 12.0
color = [27, 136, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_squad_sticky_grenade"
name = "Sticky Grenade"
trigger = { type = "ability_cast", ability_ids = [4447472994746368] }
duration_secs = 7.0
color = [213, 112, 31, 255]
difficulties = ["veteran", "master"]
