# Shrine of Silence
# 5 boss(es)

[area]
name = "Shrine of Silence"
area_id = 137438987149

# ─── corrupted_vorantikus ───
[[boss]]
id = "corrupted_vorantikus"
name = "Corrupted Vorantikus"
difficulties = ["master", "veteran"]
npc_names = ["Corrupted Vorantikus"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "corrupted_vorantikus_tantrum"
name = "Tantrum"
trigger = { type = "ability_cast", ability_ids = [4680784208199680] }
duration_secs = 60.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corrupted_vorantikus_cleaving_strike"
name = "Cleaving Strike"
trigger = { type = "ability_cast", ability_ids = [4680346121535488] }
duration_secs = 10.0
color = [228, 112, 34, 255]
difficulties = ["veteran", "master"]

# ─── kirba_the_forgotten ───
[[boss]]
id = "kirba_the_forgotten"
name = "Kirba, the Forgotten"
difficulties = ["master", "veteran"]
npc_names = ["Kirba, the Forgotten"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kirba_the_forgotten_blast_of_hatred"
name = "Blast of Hatred"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [128, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_forceful_presence"
name = "Forceful Presence"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_blast_of_hatred" }
duration_secs = 10.0
color = [39, 220, 211, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_furious_bellow"
name = "Furious Bellow"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_forceful_presence" }
duration_secs = 10.0
color = [213, 117, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_enraged_stomp"
name = "Enraged Stomp"
trigger = { type = "ability_cast", ability_ids = [4677219385344000] }
duration_secs = 12.0
color = [228, 44, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_ancient_s_rage"
name = "Ancient's Rage"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_furious_bellow" }
duration_secs = 5.0
color = [220, 218, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_ancient_s_rage_2"
name = "Ancient's Rage_"
trigger = { type = "ability_cast", ability_ids = [4677709011615744] }
duration_secs = 61.0
color = [220, 217, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_forceful_presence_2"
name = "Forceful Presence_"
trigger = { type = "ability_cast", ability_ids = [4676824248352768] }
duration_secs = 15.0
color = [25, 213, 208, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_furious_bellow_2"
name = "Furious Bellow_"
trigger = { type = "ability_cast", ability_ids = [4677077651423232] }
duration_secs = 23.0
color = [228, 133, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_resist"
name = "Resist"
trigger = { type = "ability_cast", ability_ids = [4677064766521344] }
duration_secs = 4.3
color = [124, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_blast_of_hatred_2"
name = "Blast of Hatred_"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_resist" }
duration_secs = 15.7
color = [131, 26, 220, 255]
difficulties = ["veteran", "master"]

# ─── nil_uu ───
[[boss]]
id = "nil_uu"
name = "Nil-Uu"
difficulties = ["master", "veteran"]
npc_names = ["Nil-Uu"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "nil_uu_electrocution"
name = "Electrocution"
trigger = { type = "ability_cast", ability_ids = [811933502537728] }
duration_secs = 45.0
color = [220, 35, 32, 255]
difficulties = ["veteran", "master"]

# ─── the_curse ───
[[boss]]
id = "the_curse"
name = "The Curse"
difficulties = ["master", "veteran"]
npc_names = ["The Curse"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_curse_forceful_slam"
name = "Forceful Slam"
trigger = { type = "combat_start" }
duration_secs = 8.0
color = [132, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_forceful_slam_2"
name = "Forceful Slam_"
trigger = { type = "ability_cast", ability_ids = [4684585254256640] }
duration_secs = 11.0
color = [126, 30, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_summon_the_corrupted"
name = "Summon the Corrupted"
trigger = { type = "combat_start" }
duration_secs = 12.0
color = [220, 208, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_summon_the_corrupted_2"
name = "Summon the Corrupted_"
trigger = { type = "ability_cast", ability_ids = [4684589549223936] }
duration_secs = 46.0
color = [203, 205, 36, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_corrupt_the_weak"
name = "Corrupt the Weak"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [228, 110, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_corrupt_the_weak_2"
name = "Corrupt the Weak_"
trigger = { type = "ability_cast", ability_ids = [4684593844191232] }
duration_secs = 74.0
color = [213, 116, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_curse_creeping_roots"
name = "Creeping Roots"
trigger = { type = "ability_cast", ability_ids = [4695185233543168] }
duration_secs = 31.0
color = [24, 136, 41, 255]
difficulties = ["veteran", "master"]

# ─── voss_mystics ───
[[boss]]
id = "voss_mystics"
name = "Voss Mystics"
difficulties = ["master", "veteran"]
npc_names = ["Voss Mystics"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "voss_mystics_lightning_storm"
name = "Lightning Storm"
trigger = { type = "combat_start" }
duration_secs = 16.0
color = [34, 44, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_force_push"
name = "Force Push"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [228, 31, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_corrupted_spirit"
name = "Corrupted Spirit "
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [8, 136, 15, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_light_beam"
name = "Light Beam"
trigger = { type = "combat_start" }
duration_secs = 8.0
color = [213, 199, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_force_push_2"
name = "Force Push_"
trigger = { type = "ability_cast", ability_ids = [4677717601550336] }
duration_secs = 31.0
color = [228, 39, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_light_beam_2"
name = "Light Beam_"
trigger = { type = "ability_cast", ability_ids = [4679573027422208] }
duration_secs = 31.0
color = [211, 213, 38, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_corrupted_spirit_2"
name = "Corrupted Spirit_"
trigger = { type = "ability_cast", ability_ids = [4679839315394560] }
duration_secs = 31.0
color = [19, 128, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voss_mystics_lightning_storm_2"
name = "Lightning Storm_"
trigger = { type = "ability_cast", ability_ids = [4679568732454912] }
duration_secs = 21.0
color = [25, 213, 212, 255]
difficulties = ["veteran", "master"]
