# Spirit of Vengeance
# 5 boss(es)

[area]
name = "Spirit of Vengeance"
area_id = 833571547775795

# ─── bask_sunn ───
[[boss]]
id = "bask_sunn"
name = "Bask Sunn"
difficulties = ["master", "veteran"]
npc_names = ["Bask Sunn"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "bask_sunn_restrain"
name = "Restrain"
trigger = { type = "ability_cast", ability_ids = [4429206498836480] }
duration_secs = 30.0
color = [228, 30, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bask_sunn_stay_away"
name = "Stay away_"
trigger = { type = "effect_applied", effect_ids = [4433862243385604] }
duration_secs = 6.0
color = [213, 123, 31, 255]
difficulties = ["veteran", "master"]

# ─── goldie ───
[[boss]]
id = "goldie"
name = "Goldie"
difficulties = ["master", "veteran"]
npc_names = ["Goldie"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "goldie_slam"
name = "Slam"
trigger = { type = "ability_cast", ability_ids = [4439110693421056] }
duration_secs = 33.0
color = [213, 34, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "goldie_swipe"
name = "Swipe"
trigger = { type = "ability_cast", ability_ids = [4439097808519168] }
duration_secs = 8.0
color = [31, 195, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "goldie_swipe_2"
name = "Swipe_"
trigger = { type = "ability_cast", ability_ids = [4439102103486464] }
duration_secs = 10.0
color = [39, 217, 220, 255]
difficulties = ["veteran", "master"]

# ─── gorga_brak ───
[[boss]]
id = "gorga_brak"
name = "Gorga Brak"
difficulties = ["master", "veteran"]
npc_names = ["Gorga Brak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gorga_brak_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [4433883718221824] }
duration_secs = 20.0
color = [25, 213, 208, 255]
difficulties = ["veteran", "master"]

# ─── heta_kol ───
[[boss]]
id = "heta_kol"
name = "Heta Kol"
difficulties = ["master", "veteran"]
npc_names = ["Heta Kol"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "heta_kol_flamethrower"
name = "Flamethrower"
trigger = { type = "ability_cast", ability_ids = [4438419203686400] }
duration_secs = 15.0
color = [228, 139, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "heta_kol_grenade"
name = "Grenade"
trigger = { type = "ability_cast", ability_ids = [4438024066695168] }
duration_secs = 9.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "heta_kol_lockdown"
name = "Lockdown"
trigger = { type = "ability_cast", ability_ids = [4437001864478720] }
duration_secs = 30.0
color = [220, 39, 196, 255]
difficulties = ["veteran", "master"]

# ─── troya_ajak ───
[[boss]]
id = "troya_ajak"
name = "Troya Ajak"
difficulties = ["master", "veteran"]
npc_names = ["Troya Ajak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "troya_ajak_knocback_pickoff"
name = "Knocback + Pickoff"
trigger = { type = "ability_cast", ability_ids = [4432844336136192] }
duration_secs = 15.0
color = [213, 107, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "troya_ajak_songbrid"
name = "Songbrid_"
trigger = { type = "ability_cast", ability_ids = [4432586638098432] }
duration_secs = 6.0
color = [213, 200, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "troya_ajak_songbird"
name = "Songbird"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [213, 199, 19, 255]
difficulties = ["veteran", "master"]
