# The Black Talon
# 4 boss(es)

[area]
name = "The Black Talon"
area_id = 833571547775679

# ─── commander_ghulil ───
[[boss]]
id = "commander_ghulil"
name = "Commander Ghulil"
difficulties = ["master", "veteran"]
npc_names = ["Commander Ghulil"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_ghulil_plasma_probe"
name = "Plasma Probe"
trigger = { type = "ability_cast", ability_ids = [2042587661729792] }
duration_secs = 11.0
color = [220, 190, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_ghulil_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 90.0
color = [220, 42, 39, 255]
difficulties = ["master"]

# ─── gxr_5_sabotage_droid ───
[[boss]]
id = "gxr_5_sabotage_droid"
name = "GXR-5 Sabotage Droid"
difficulties = ["master", "veteran"]
npc_names = ["GXR-5 Sabotage Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gxr_5_sabotage_droid_full_auto"
name = "Full Auto"
trigger = { type = "ability_cast", ability_ids = [2529645543030784] }
duration_secs = 18.0
color = [220, 44, 39, 255]
difficulties = ["veteran", "master"]

# ─── gxr_7_command_droid ───
[[boss]]
id = "gxr_7_command_droid"
name = "GXR-7 Command Droid"
difficulties = ["master", "veteran"]
npc_names = ["GXR-7 Command Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gxr_7_command_droid_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 90.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gxr_7_command_droid_power_punch"
name = "Power Punch"
trigger = { type = "ability_cast", ability_ids = [2517117123428352] }
duration_secs = 20.0
color = [205, 106, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gxr_7_command_droid_power_blast"
name = "Power Blast"
trigger = { type = "ability_cast", ability_ids = [2517112828461056] }
duration_secs = 12.0
color = [224, 228, 27, 255]
difficulties = ["veteran", "master"]

# ─── yadira_ban ───
[[boss]]
id = "yadira_ban"
name = "Yadira Ban"
difficulties = ["master", "veteran"]
npc_names = ["Yadira Ban"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "yadira_ban_force_charge"
name = "Force Charge"
trigger = { type = "ability_cast", ability_ids = [2031970502574080] }
duration_secs = 9.0
color = [225, 65, 243, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "yadira_ban_cyclone_nova"
name = "Cyclone Nova"
trigger = { type = "ability_cast", ability_ids = [850738532057088] }
duration_secs = 19.5
color = [39, 220, 214, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "yadira_ban_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 70.0
color = [228, 40, 43, 255]
difficulties = ["master"]
