# The Nathema Conspiracy
# 4 boss(es)

[area]
name = "The Nathema Conspiracy"
area_id = 833571547775764

# ─── ancient_guardian_droid ───
[[boss]]
id = "ancient_guardian_droid"
name = "Ancient Guardian Droid"
difficulties = ["master", "veteran"]
npc_names = ["Ancient Guardian Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "ancient_guardian_droid_rocket_stomp"
name = "Rocket Stomp"
trigger = { type = "ability_cast", ability_ids = [4164232786477056] }
duration_secs = 20.0
color = [220, 45, 39, 255]
difficulties = ["veteran", "master"]

# ─── gemini_16 ───
[[boss]]
id = "gemini_16"
name = "GEMINI 16"
difficulties = ["master", "veteran"]
npc_names = ["GEMINI 16"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gemini_16_beam"
name = "Beam"
trigger = { type = "ability_cast", ability_ids = [4163472577265664] }
duration_secs = 17.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gemini_16_adds_vm"
name = "Adds VM"
trigger = { type = "ability_cast", ability_ids = [4162446080081920] }
duration_secs = 45.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gemini_16_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4162235626684416] }
duration_secs = 30.0
color = [21, 144, 27, 255]
difficulties = ["veteran", "master"]

# ─── vinn_atrius_zildrog ───
[[boss]]
id = "vinn_atrius_zildrog"
name = "Vinn Atrius & Zildrog"
difficulties = ["master", "veteran"]
npc_names = ["Vinn Atrius & Zildrog"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle_1st"
name = "Lifeforce Shackle 1st"
trigger = { type = "combat_start" }
duration_secs = 19.0
color = [220, 59, 150, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_force_blast_1st"
name = "Force Blast 1st"
trigger = { type = "combat_start" }
duration_secs = 9.0
color = [179, 182, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle"
name = "Lifeforce Shackle"
trigger = { type = "effect_applied", effect_ids = [4159297869054208] }
duration_secs = 17.0
color = [213, 51, 152, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_rupture"
name = "Rupture"
trigger = { type = "ability_cast", ability_ids = [4160706618327040] }
duration_secs = 20.0
color = [220, 114, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lightning_storm"
name = "Lightning Storm"
trigger = { type = "ability_cast", ability_ids = [4160693733425152] }
duration_secs = 20.0
color = [34, 50, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_horizon_lance"
name = "Horizon Lance"
trigger = { type = "ability_cast", ability_ids = [4166221356335104] }
duration_secs = 17.0
color = [155, 61, 255, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_surging_strike"
name = "Surging Strike"
trigger = { type = "ability_cast", ability_ids = [4158975746506752] }
duration_secs = 20.0
color = [148, 77, 236, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_force_blast"
name = "Force Blast"
trigger = { type = "ability_cast", ability_ids = [4160685143490560] }
duration_secs = 17.0
color = [190, 190, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_breath_of_izax"
name = "Breath of Izax"
trigger = { type = "ability_cast", ability_ids = [4168261465800704] }
duration_secs = 30.0
color = [31, 199, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle_2"
name = "Lifeforce Shackle_"
trigger = { type = "effect_applied", effect_ids = [4180033971159344] }
duration_secs = 17.0
color = [228, 34, 172, 255]
difficulties = ["veteran", "master"]

# ─── voreclaw ───
[[boss]]
id = "voreclaw"
name = "Voreclaw"
difficulties = ["master", "veteran"]
npc_names = ["Voreclaw"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "voreclaw_power_leap"
name = "Power Leap"
trigger = { type = "ability_cast", ability_ids = [4152992857063424] }
duration_secs = 17.0
color = [205, 26, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voreclaw_burrow"
name = "Burrow"
trigger = { type = "ability_cast", ability_ids = [4157631421743104] }
duration_secs = 30.0
color = [220, 122, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voreclaw_burrowed"
name = "Burrowed"
trigger = { type = "ability_cast", ability_ids = [4157631421743104] }
duration_secs = 15.0
color = [220, 39, 41, 255]
difficulties = ["veteran", "master"]
