# The Foundry
# 3 boss(es)

[area]
name = "The Foundry"
area_id = 833571547775681

# ─── burrower_matriarch ───
[[boss]]
id = "burrower_matriarch"
name = "Burrower Matriarch"
difficulties = ["master", "veteran"]
npc_names = ["Burrower Matriarch"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "burrower_matriarch_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 70.0
color = [220, 26, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "burrower_matriarch_spit_pool"
name = "Spit Pool"
trigger = { type = "ability_cast", ability_ids = [2316967352467456] }
duration_secs = 9.0
color = [220, 121, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "burrower_matriarch_knocback"
name = "Knocback"
trigger = { type = "ability_cast", ability_ids = [2541984984072192] }
duration_secs = 12.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

# ─── foundry_guardian ───
[[boss]]
id = "foundry_guardian"
name = "Foundry Guardian"
difficulties = ["master", "veteran"]
npc_names = ["Foundry Guardian"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "foundry_guardian_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 90.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "foundry_guardian_molten_burst"
name = "Molten Burst"
trigger = { type = "ability_cast", ability_ids = [2521790047846400] }
duration_secs = 30.0
color = [220, 122, 32, 255]
difficulties = ["veteran", "master"]

# ─── hk_47 ───
[[boss]]
id = "hk_47"
name = "HK-47"
difficulties = ["master", "veteran"]
npc_names = ["HK-47"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "hk_47_iddle"
name = "Iddle"
trigger = { type = "ability_cast", ability_ids = [2518195160219648] }
duration_secs = 18.5
color = [18, 144, 17, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_kick"
name = "Kick"
trigger = { type = "ability_cast", ability_ids = [2518165095448576] }
duration_secs = 30.0
color = [213, 128, 38, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_core_enrage"
name = "Core Enrage"
trigger = { type = "effect_applied", effect_ids = [2517920282312704] }
duration_secs = 15.0
color = [220, 46, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_enrage_core"
name = "Enrage Core"
trigger = { type = "ability_cast", ability_ids = [2518182275317760] }
duration_secs = 18.5
color = [210, 213, 38, 255]
difficulties = ["veteran", "master"]
