# The Red Reaper
# 3 boss(es)

[area]
name = "The Red Reaper"
area_id = 833571547775686

# ─── darth_ikoral ───
[[boss]]
id = "darth_ikoral"
name = "Darth Ikoral"
difficulties = ["master", "veteran"]
npc_names = ["Darth Ikoral"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "darth_ikoral_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 300.0
color = [228, 36, 34, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_ikoral_empowered_mm"
name = "Empowered MM"
trigger = { type = "ability_cast", ability_ids = [2496982316744704] }
duration_secs = 45.0
color = [220, 125, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_ikoral_empowered_vm"
name = "Empowered VM"
trigger = { type = "ability_cast", ability_ids = [2496982316744704] }
duration_secs = 50.0
color = [220, 118, 26, 255]
difficulties = ["veteran"]

# ─── lord_kherus ───
[[boss]]
id = "lord_kherus"
name = "Lord Kherus"
difficulties = ["master", "veteran"]
npc_names = ["Lord Kherus"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "lord_kherus_drain_25"
name = "Drain 25"
trigger = { type = "boss_hp_below", hp_percent = 25.0, boss_name = "Lord Kherus" }
duration_secs = 25.0
color = [39, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lord_kherus_drain"
name = "Drain"
trigger = { type = "ability_cast", ability_ids = [2485635013148672] }
duration_secs = 30.0
color = [25, 209, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lord_kherus_whirlwind"
name = "Whirlwind"
trigger = { type = "ability_cast", ability_ids = [2495281509695488] }
duration_secs = 30.0
color = [205, 40, 36, 255]
difficulties = ["veteran", "master"]

# ─── sv_3_eradicator ───
[[boss]]
id = "sv_3_eradicator"
name = "SV-3 Eradicator"
difficulties = ["master", "veteran"]
npc_names = ["SV-3 Eradicator"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "sv_3_eradicator_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [2491059556843520] }
duration_secs = 16.5
color = [220, 115, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sv_3_eradicator_red_beam"
name = "Red Beam"
trigger = { type = "ability_cast", ability_ids = [2496046013874176] }
duration_secs = 18.0
color = [228, 27, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sv_3_eradicator_blue_beam_setup"
name = "Blue Beam Setup"
trigger = { type = "ability_cast", ability_ids = [2496273647140864] }
duration_secs = 8.0
color = [32, 220, 215, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sv_3_eradicator_blue_beam"
name = "Blue Beam"
trigger = { type = "timer_expires", timer_id = "sv_3_eradicator_blue_beam_setup" }
duration_secs = 10.0
color = [26, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sv_3_eradicator_blue_beam_2"
name = "Blue Beam_"
trigger = { type = "ability_cast", ability_ids = [2496046013874176] }
duration_secs = 10.0
color = [31, 201, 213, 255]
difficulties = ["veteran", "master"]
