# The False Emperor
# 5 boss(es)

[area]
name = "The False Emperor"
area_id = 833571547775673

# ─── darth_malgus ───
[[boss]]
id = "darth_malgus"
name = "Darth Malgus"
difficulties = ["master", "veteran"]
npc_names = ["Darth Malgus"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "darth_malgus_unlimited_power"
name = "Unlimited Power"
trigger = { type = "ability_cast", ability_ids = [2467746474360832] }
duration_secs = 20.0
color = [220, 26, 200, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_malgus_doubt"
name = "Doubt"
trigger = { type = "ability_cast", ability_ids = [2161579730665472] }
duration_secs = 60.0
color = [19, 106, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_malgus_choke"
name = "Choke"
trigger = { type = "ability_cast", ability_ids = [2161579730665472] }
duration_secs = 18.0
color = [220, 32, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_malgus_choke_end"
name = "Choke END"
trigger = { type = "ability_cast", ability_ids = [2163151688695808] }
duration_secs = 15.0
color = [12, 136, 30, 255]
difficulties = ["veteran", "master"]

# ─── jindo_krey ───
[[boss]]
id = "jindo_krey"
name = "Jindo Krey"
difficulties = ["master", "veteran"]
npc_names = ["Jindo Krey"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "jindo_krey_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [1626349496172544] }
duration_secs = 32.0
color = [32, 81, 182, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_rail_shot"
name = "Rail Shot"
trigger = { type = "ability_cast", ability_ids = [1626413920681984] }
duration_secs = 15.0
color = [98, 136, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_jet_charge"
name = "Jet Charge"
trigger = { type = "ability_cast", ability_ids = [1626899251986432] }
duration_secs = 12.0
color = [190, 87, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_missile_barrage"
name = "Missile Barrage"
trigger = { type = "ability_cast", ability_ids = [1593385622175744] }
duration_secs = 39.0
color = [236, 20, 0, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_missile_blast"
name = "Missile Blast"
trigger = { type = "ability_cast", ability_ids = [1593381327208448] }
duration_secs = 12.0
color = [190, 11, 180, 255]
difficulties = ["veteran", "master"]

# ─── prototype_a_14_prototype_b_16 ───
[[boss]]
id = "prototype_a_14_prototype_b_16"
name = "Prototype A-14 & Prototype B-16"
difficulties = ["master", "veteran"]
npc_names = ["Prototype A-14 & Prototype B-16"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "prototype_a_14_prototype_b_16_swap_a_14"
name = "Swap A-14"
trigger = { type = "effect_applied", effect_ids = [1790223973351685] }
duration_secs = 30.0
color = [220, 39, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prototype_a_14_prototype_b_16_swap_b_16"
name = "Swap B-16"
trigger = { type = "effect_applied", effect_ids = [1790223973351685] }
duration_secs = 30.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

# ─── sith_entity ───
[[boss]]
id = "sith_entity"
name = "Sith Entity"
difficulties = ["master", "veteran"]
npc_names = ["Sith Entity"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "sith_entity_affliction_1st"
name = "Affliction 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [12, 136, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knocback_1st"
name = "Knocback 1st"
trigger = { type = "timer_expires", timer_id = "sith_entity_affliction_1st" }
duration_secs = 5.0
color = [43, 40, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning_1st"
name = "Force Lightning 1st"
trigger = { type = "timer_expires", timer_id = "sith_entity_knocback_1st" }
duration_secs = 5.0
color = [119, 27, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 300.0
color = [228, 38, 34, 255]
difficulties = ["master"]

[[boss.timer]]
id = "sith_entity_mass_lightning"
name = "Mass Lightning"
trigger = { type = "ability_cast", ability_ids = [2158289785716736] }
duration_secs = 30.0
color = [243, 103, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2157117259644928] }
duration_secs = 10.0
color = [20, 167, 46, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [2157121554612224] }
duration_secs = 30.0
color = [35, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning"
name = "Force Lightning"
trigger = { type = "ability_cast", ability_ids = [2157228928794624] }
duration_secs = 20.0
color = [128, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knockback_a"
name = "Knockback A"
trigger = { type = "timer_expires", timer_id = "c253d7aa-d4a2-4831-adbd-7cfd3d77e327" }
duration_secs = 5.0
color = [35, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning_a"
name = "Force Lightning A"
trigger = { type = "timer_expires", timer_id = "sith_entity_knockback_a" }
duration_secs = 5.0
color = [127, 32, 220, 255]
difficulties = ["veteran", "master"]

# ─── tregg_the_destroyer ───
[[boss]]
id = "tregg_the_destroyer"
name = "Tregg the Destroyer"
difficulties = ["master", "veteran"]
npc_names = ["Tregg the Destroyer"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "tregg_the_destroyer_leap_slash"
name = "Leap + Slash"
trigger = { type = "ability_cast", ability_ids = [2315786236461056] }
duration_secs = 18.0
color = [220, 34, 26, 255]
difficulties = ["veteran", "master"]
