# The Battle of Ilum
# 4 boss(es)

[area]
name = "The Battle of Ilum"
area_id = 833571547775672

# ─── darth_serevin ───
[[boss]]
id = "darth_serevin"
name = "Darth Serevin"
difficulties = ["master", "veteran"]
npc_names = ["Darth Serevin"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "darth_serevin_dark_blast_1st"
name = "Dark Blast 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [140, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_affliction_1st"
name = "Affliction 1st"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [159, 19, 123, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_electro_storm_1st"
name = "Electro Storm 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [101, 63, 236, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2074314585145344] }
duration_secs = 15.0
color = [167, 20, 129, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "darth_serevin_affliction_mm"
name = "Affliction MM"
trigger = { type = "ability_cast", ability_ids = [2520995478896640] }
duration_secs = 20.0
color = [182, 5, 141, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_serevin_electro_storm"
name = "Electro Storm"
trigger = { type = "ability_cast", ability_ids = [2074318880112640] }
duration_secs = 45.0
color = [101, 63, 236, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "darth_serevin_electro_storm_mm"
name = "Electro Storm MM"
trigger = { type = "ability_cast", ability_ids = [2520986888962048] }
duration_secs = 45.0
color = [101, 63, 236, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_serevin_force_explosion"
name = "Force Explosion"
trigger = { type = "ability_cast", ability_ids = [2138734799618048] }
duration_secs = 20.0
color = [220, 36, 32, 255]
difficulties = ["veteran", "master"]

# ─── gark_the_indomitable ───
[[boss]]
id = "gark_the_indomitable"
name = "Gark the Indomitable"
difficulties = ["master", "veteran"]
npc_names = ["Gark the Indomitable"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gark_the_indomitable_stockstrike"
name = "Stockstrike"
trigger = { type = "ability_cast", ability_ids = [1677953528233984] }
duration_secs = 30.0
color = [121, 74, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gark_the_indomitable_hail_of_bolts"
name = "Hail Of Bolts"
trigger = { type = "ability_cast", ability_ids = [1677919168495616] }
duration_secs = 20.0
color = [213, 31, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gark_the_indomitable_concussive_round"
name = "Concussive Round"
trigger = { type = "effect_applied", effect_ids = [2541662861525256] }
duration_secs = 60.0
color = [197, 185, 11, 255]
difficulties = ["veteran", "master"]

# ─── krel_thak ───
[[boss]]
id = "krel_thak"
name = "Krel Thak"
difficulties = ["master", "veteran"]
npc_names = ["Krel Thak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "krel_thak_dirty_kick"
name = "Dirty Kick"
trigger = { type = "ability_cast", ability_ids = [2068301630930944] }
duration_secs = 30.0
color = [190, 170, 22, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_thermal_grenade"
name = "Thermal Grenade"
trigger = { type = "ability_cast", ability_ids = [2068318810800128] }
duration_secs = 15.0
color = [151, 105, 59, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_dirty_kick_mm"
name = "Dirty Kick MM"
trigger = { type = "ability_cast", ability_ids = [2522425703006208] }
duration_secs = 30.0
color = [205, 187, 36, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_thermal_grenade_mm"
name = "Thermal Grenade MM"
trigger = { type = "ability_cast", ability_ids = [2522464357711872] }
duration_secs = 15.0
color = [151, 109, 27, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_shielded_mm"
name = "Shielded MM"
trigger = { type = "effect_applied", effect_ids = [2522455767777537] }
duration_secs = 15.0
color = [43, 197, 205, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_shielded"
name = "Shielded"
trigger = { type = "effect_applied", effect_ids = [2068215731585282] }
duration_secs = 15.0
color = [36, 205, 191, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_shield_probe"
name = "Shield Probe"
trigger = { type = "timer_expires", timer_id = "krel_thak_shielded_mm" }
duration_secs = 15.0
color = [23, 197, 168, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "krel_thak_in_cover"
name = "In Cover"
trigger = { type = "effect_applied", effect_ids = [2068211436617728] }
duration_secs = 10.0
color = [21, 79, 182, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_in_cover_mm"
name = "In Cover MM"
trigger = { type = "effect_applied", effect_ids = [2522447177842688] }
duration_secs = 10.0
color = [19, 85, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_defense_screen"
name = "Defense Screen"
trigger = { type = "timer_expires", timer_id = "krel_thak_in_cover" }
duration_secs = 20.0
color = [5, 76, 174, 255]
difficulties = ["veteran", "master"]

# ─── velasu_graege_drinda_zel ───
[[boss]]
id = "velasu_graege_drinda_zel"
name = "Velasu Graege & Drinda-Zel"
difficulties = ["master", "veteran"]
npc_names = ["Velasu Graege & Drinda-Zel"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "velasu_graege_drinda_zel_concussion_charge_vm"
name = "Concussion Charge VM"
trigger = { type = "ability_cast", ability_ids = [2058079608766464] }
duration_secs = 13.5
color = [220, 163, 59, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "velasu_graege_drinda_zel_concussion_charge_mm"
name = "Concussion Charge MM"
trigger = { type = "ability_cast", ability_ids = [2522361278496768] }
duration_secs = 13.5
color = [197, 160, 65, 255]
difficulties = ["master"]

[[boss.timer]]
id = "velasu_graege_drinda_zel_concussion_missile_mm"
name = "Concussion Missile MM"
trigger = { type = "ability_cast", ability_ids = [2522365573464064] }
duration_secs = 15.0
color = [197, 35, 145, 255]
difficulties = ["master"]

[[boss.timer]]
id = "velasu_graege_drinda_zel_concussion_missile_vm"
name = "Concussion Missile VM"
trigger = { type = "ability_cast", ability_ids = [2058908537454592] }
duration_secs = 15.0
color = [197, 41, 124, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "velasu_graege_drinda_zel_force_lightning_mm"
name = "Force Lightning MM"
trigger = { type = "effect_applied", effect_ids = [2522344098627843] }
duration_secs = 12.0
color = [150, 39, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "velasu_graege_drinda_zel_force_lightning_vm"
name = "Force Lightning VM"
trigger = { type = "effect_applied", effect_ids = [2057937874845954] }
duration_secs = 12.0
color = [161, 39, 220, 255]
difficulties = ["veteran"]
